mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('pokus/', include('pokus.urls', namespace="pokus")),
]

pokus/urls.py
from django.urls import path
from pokus import views

app_name = 'pokus'

urlpatterns = [
    path("register/", views.register_request, name="register"),
    path("login/", views.login_request, name="login"),
    path("base/", views.base, name="base"),
    path("add_new/", views.add_new, name="add_new"),
    path('event/<int:event_id>/', views.event_detail, name='event_detail'),
    path("logout", views.logout_request, name= "logout"),

]

pokus/models.py
from django.db import models
from django.contrib.auth.models import User

class DateTimeOption(models.Model):
    date_time = models.DateTimeField()
    voter_name = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return str(self.date_time)
    

class Event(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    duration = models.IntegerField(default=60)  # Duration in minutes

    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    date_time_options = models.ManyToManyField('DateTimeOption')  

    id = models.AutoField(primary_key=True)

    def __str__(self):
        return self.title

pokus/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User 
from django.core.exceptions import ValidationError

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
            return user
        
class ActionForm(forms.Form):
    title = forms.CharField(max_length=100)
    description  =forms.CharField(widget=forms.Textarea)
    duration = forms.IntegerField(min_value=10, max_value=180, initial=60, widget=forms.TextInput(attrs={'type': 'range', 'step': '10'}))

    date_time_options_1 = forms.DateTimeField(
        label='Date and Time options',
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        input_formats=['%Y-%m-%dT%H:%M'],
        required=False,
    )

    date_time_options_2 = forms.DateTimeField(
        label='Date and Time options',
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        input_formats=['%Y-%m-%dT%H:%M'],
        required=False,

    )

    date_time_options_3 = forms.DateTimeField(
        label='Date and Time options',
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        input_formats=['%Y-%m-%dT%H:%M'],
        required=False,
    )

    date_time_options_4 = forms.DateTimeField(
        label='Date and Time options',
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        input_formats=['%Y-%m-%dT%H:%M'],
        required=False,
    )

    date_time_options_5 = forms.DateTimeField(
        label='Date and Time options',
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        input_formats=['%Y-%m-%dT%H:%M'],
        required=False,
    )

    date_time_options_6 = forms.DateTimeField(
        label='Date and Time options',
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        input_formats=['%Y-%m-%dT%H:%M'],
        required=False,
    )

    date_time_options_7 = forms.DateTimeField(
        label='Date and Time options',
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        input_formats=['%Y-%m-%dT%H:%M'],
        required=False,
    )

    date_time_options_8 = forms.DateTimeField(
        label='Date and Time options',
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        input_formats=['%Y-%m-%dT%H:%M'],
        required=False,
    )

    date_time_options_9 = forms.DateTimeField(
        label='Date and Time options',
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        input_formats=['%Y-%m-%dT%H:%M'],
        required=False,
    )

    date_time_options_10 = forms.DateTimeField(
        label='Date and Time options',
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        input_formats=['%Y-%m-%dT%H:%M'],
        required=False,
    )

    

pokus/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import NewUserForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm 
from .forms import ActionForm
from .models import Event, DateTimeOption
from django.http import HttpResponseRedirect
from django.urls import reverse 
from django.utils import timezone
from django.contrib.auth.decorators import login_required


def base(request):
    return render(request, 'pokus/base.html')


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("pokus:login")
        else:
            messages.error(request, "Unsuccessful registration. Invalid information.")
    else:
        form = NewUserForm()

    return render(
        request=request,
        template_name="pokus/register.html",
        context={"register_form": form},
    )

    
def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				return redirect("pokus:add_new")
                
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="pokus/login.html", context={"login_form":form})

def logout_request(request):
	logout(request)
	return redirect("pokus:login")


@login_required
def add_new(request):
    if request.method == 'POST':
        form = ActionForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            duration = form.cleaned_data['duration']

            event = Event(
                title=title,
                description=description,
                duration=duration,
                created_by=request.user,  # request.user to get the currently logged-in user
                created_at=timezone.now(),
            )
            event.save()

            for i in range(1, 11): 
                date_time_field_name = f'date_time_options_{i}'
                date_time = form.cleaned_data.get(date_time_field_name)
                if date_time:
                    date_time_option = DateTimeOption(date_time=date_time)
                    date_time_option.save()
                    event.date_time_options.add(date_time_option)

            return HttpResponseRedirect(reverse('pokus:event_detail', args=[event.id]))
        
        else:

            messages.error(request, 'Form submission is not valid. Please correct the errors.')

    else:
        form = ActionForm()

    return render(request, 'pokus/add_new.html', {'form': form})


from django.shortcuts import render, get_object_or_404, redirect
from .models import Event, DateTimeOption 


def event_detail(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    date_time_options = event.date_time_options.all()

    if request.method == 'POST':
        time_slot_id = request.POST.get('time_slot')  
        user_name = request.POST.get('user_name')

        # Get the selected DateTimeOption
        selected_time_slot = get_object_or_404(DateTimeOption, pk=time_slot_id)

        # Update 
        selected_time_slot.voter_name = user_name
        selected_time_slot.save()

        return redirect('pokus:event_detail', event_id=event.id)

    return render(request, 'pokus/event_detail.html', {'event': event, 'date_time_options': date_time_options})

pokus/templates/pokus/add_new.html
{% extends 'pokus/base.html' %}

{% block content %}

<form action="{% url 'pokus:add_new' %}" method="post">

{% csrf_token %}

  <div class="container">
    <h1>Create a new action</h1>
    <hr>

    <label for="title"><b>Title</b></label>
    <input type="text" placeholder="Enter Title" name="title" required>

    <hr>

    <label for="description"><b>Description</b></label>
    <textarea placeholder="Enter Description" name="description" rows="4" required></textarea>

    <hr>

    <label for="duration"><b>Duration</b></label>
    <input type="range" name="duration" min="10" max="180" step="10" value="60" class="slider">
    <span id="duration-label">60 min.</span>
  
    <hr>

    <label for="date_time_options"><b>Date and Time Options</b></label>
    <div id="date_time_options_container">
        <div class="date_time_option">
            <input type="datetime-local" placeholder="Select Date and Time" name="date_time_options_1" required>
        </div>
    </div>

    <button type="button" class="smallbtn" id="add_date_time_option">Add Date and Time Option</button>

    <hr>

    <button type="submit" class="registerbtn">Create Action</button>
</div>

<script>
    const durationSlider = document.querySelector('input[name="duration"]');
    const durationLabel = document.getElementById("duration-label");

    durationSlider.addEventListener("input", () => {
        durationLabel.textContent = durationSlider.value + " min.";
    });

    const dateOptionsContainer = document.getElementById("date_time_options_container");
    const addDateOptionButton = document.getElementById("add_date_time_option");

    let timeSlotCounter = 2;

    addDateOptionButton.addEventListener("click", () => {
        const dateOptionDiv = document.createElement("div");
        dateOptionDiv.classList.add("date_time_option");

        const newInput = document.createElement("input");
        newInput.type = "datetime-local";
        newInput.placeholder = "Select Date and Time";

        newInput.name = "date_time_options_" + timeSlotCounter;
        newInput.required = true;

        timeSlotCounter++;
        
        const deleteButton = document.createElement("button");
        deleteButton.type = "button";
        deleteButton.classList.add("smallbtn");
        deleteButton.textContent = "Delete";
        deleteButton.addEventListener("click", () => {
        dateOptionsContainer.removeChild(dateOptionDiv);
        }); 
     

        dateOptionDiv.appendChild(newInput);
        dateOptionDiv.appendChild(deleteButton);

        dateOptionsContainer.appendChild(dateOptionDiv);
    });
</script>
{% endblock %}

pokus/templates/pokus/base.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {box-sizing: border-box;}

body { 
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

form {border: 3px solid #f1f1f1;} 

.header {
  overflow: hidden;
  background-color: #f1f1f1;
  padding: 20px 10px;
}

.header a {
  float: left;
  color: black;
  text-align: center;
  padding: 12px;
  text-decoration: none;
  font-size: 18px; 
  line-height: 25px;
  border-radius: 4px;
}

.header a.logo {
  font-size: 20px;
  background-color: #0f5e61;
  color: white;
}

.header a:hover {
  background-color: #ddd;
  color: black;
}

hr {
    border: 1px solid #f1f1f1;
    margin-bottom: 25px;
}

.header a.active {
  background-color: #0f5e61;
  color: white;
}

.header a.center {
    background-color: #0f5e61;
    color: white;
    margin: 0;
    position: absolute;
    left: 50%;
    -ms-transform: translate(-50%, -50%);
    transform: translate(-50%, -50%);
}

.header-right {
  float: right;
}

.username {
    display: inline-block;
    background-color: #f58634; /* Change this color to your desired color */
    color: white; /* Text color */
    padding: 15px 25px;
    border-radius: 80%; /* Creates an oval shape */
}


@media screen and (max-width: 500px) {
  .header a {
    float: none;
    display: block;
    text-align: left;
  }
  
  .header-right {
    float: none;
  }
}

body {font-family: Arial, Helvetica, sans-serif;}
body {border: 3px solid #f1f1f1;} 

input[type=text], input[type=password] {
	width: 100%;
	padding: 15px;
	margin: 5px 0 22px 0;
	display: inline-block;
	background: #f1f1f1;
  border: 1px solid #ccc;
  border-radius: 4px;
}

input[type=name] {
	padding: 8px;
	margin: 5px 0 22px 0;
	display: inline-block;
	background: #f1f1f1;
  border: 1px solid #ccc;
  border-radius: 4px;
}

.slidecontainer {
  width: 100%;
}

.slider {
  -webkit-appearance: none;
  width: 100%;
  height: 15px;
  border: 1px solid #ccc;
  border-radius: 4px;
  background: #f1f1f1;
  outline: none;
  opacity: 0.7;
  -webkit-transition: .2s;
  transition: opacity .2s;
}

.slider:hover {
  opacity: 1;
}

.slider::-webkit-slider-thumb {
  -webkit-appearance: none;
  appearance: none;
  width: 25px;
  height: 25px;
  border-radius: 50%;
  background: #0f5e61;
  cursor: pointer;
}

.slider::-moz-range-thumb {
  width: 25px;
  height: 25px;
  border-radius: 50%;
  background: #0f5e61;
  cursor: pointer;
}

textarea {
  width: 100%;
  margin: 5px 0 22px 0;
  height: 100px;
  padding: 15px;
  box-sizing: border-box;
  border: 1px solid #ccc;
  border-radius: 4px;
  background-color: #f8f8f8;
  font-size: 15px;
  resize: none;
}

* {
  box-sizing: border-box;
}

.container {
  padding: 16px;
  background-color: white;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}



.btn {
  background-color: #0f5e61;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

.smallbtn {
  background-color: #0f5e61;
  color: white;
  padding: 8px 15px;
  margin: 1px 0;
  border: none;
  cursor: pointer;
  opacity: 0.9;
}

.smallbtn:hover {
  opacity: 1;
}

.btn:hover {
  opacity: 1;
}

/* Add a blue text color to links */
a {
  color: #0f5e61;
}

.signin {
  background-color: #f1f1f1;
  text-align: center;
}

body {font-family: Arial, Helvetica, sans-serif;}
form {border: 3px solid #f1f1f1;} 

input[type=text], input[type=password] {
	width: 100%;
	padding: 15px;
	margin: 5px 0 22px 0;
	display: inline-block;
	background: #f1f1f1;
  border: 1px solid #ccc;
  border-radius: 4px;
}

.slidecontainer {
  width: 100%;
}

.slider {
  -webkit-appearance: none;
  width: 100%;
  height: 15px;
  border: 1px solid #ccc;
  border-radius: 4px;
  background: #f1f1f1;
  outline: none;
  opacity: 0.7;
  -webkit-transition: .2s;
  transition: opacity .2s;
}

.slider:hover {
  opacity: 1;
}

.slider::-webkit-slider-thumb {
  -webkit-appearance: none;
  appearance: none;
  width: 25px;
  height: 25px;
  border-radius: 50%;
  background: #0f5e61;
  cursor: pointer;
}

.slider::-moz-range-thumb {
  width: 25px;
  height: 25px;
  border-radius: 50%;
  background: #0f5e61;
  cursor: pointer;
}

textarea {
  width: 100%;
  margin: 5px 0 22px 0;
  height: 100px;
  padding: 15px;
  box-sizing: border-box;
  border: 1px solid #ccc;
  border-radius: 4px;
  background-color: #f8f8f8;
  font-size: 15px;
  resize: none;
}

* {
  box-sizing: border-box;
}

.container {
  padding: 16px;
  background-color: white;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}



.registerbtn {
  background-color: #0f5e61;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

.registerbtn:hover {
  opacity: 1;
}

.smallbtn {
  background-color: #0f5e61;
  color: white;
  padding: 3px 15px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  {% comment %} width: 100%; {% endcomment %}
  opacity: 0.9;
}

.smallbtn:hover {
  opacity: 1;
}

/* Add a blue text color to links */
a {
  color: #0f5e61;
}

.signin {
  background-color: #f1f1f1;
  text-align: center;
}
</style>
</head>
<body>

  {% include 'pokus/includes/messages.html' %}
{% if user.is_authenticated %}
  <!-- username in place of "Logo" when the user is authenticated -->
  <div class="header">
    <a class="logo" href="{% url 'pokus:add_new' %}">Create a new action</a>
    <div class="header-right">
      <a href="{% url 'pokus:logout' %}">Logout</a>
      <span class="username">{{ request.user.username }}</span>
    </div>
  </div>
{% else %}

  <!-- Default header when the user is not authenticated -->
  <div class="header">
    <a href="{% url 'pokus:register' %}" class="logo">Create an account</a>
    <div class="header-right">
      <a href="{% url 'pokus:login' %}">Log in</a>
      <span class="username">Anonymous user</span>
    </div>
  </div>
{% endif %}

{% block content %}{% endblock %}

</body>
</html>

pokus/templates/pokus/event_detail.html
{% extends 'pokus/base.html' %}

  {% block content %}


    <div class="container">
        <h1>Details of the event</h1>
        <hr>

    <h2>{{ event.title }}</h2>
    <p><strong>Description: </strong>{{ event.description }}</p>
    <p><strong>Duration: </strong>{{ event.duration }} minutes</p>
    <p><strong>Created by: </strong>{{ event.created_by }} </p>
    <p><strong>Created at: </strong>{{ event.created_at }} </p>
    <p><strong>Time slot selection: </strong> </p>
  
    <ul>
      {% for time_slot in date_time_options %}
          <li>
              {{ time_slot.date_time }}
              <form method="post" style="border: none" action="{% url 'pokus:event_detail' event.id %}">
                  {% csrf_token %}
                  <input type="hidden" name="time_slot" value="{{ time_slot.id }}">
                  <input type="name" name="user_name" placeholder="Your Name">
                  <button type="submit" class="smallbtn">Vote</button>
              </form>
              {% if time_slot.voter_name %}
                  {% if time_slot.id == event.most_convenient_time.id %}
                      <strong>Most convenient time</strong>: {{ time_slot.date_time|date:"F d, Y, H:i a" }}
                  {% endif %}
              {% endif %}
          </li>
      {% endfor %}
  </ul>

  <strong>Votes:</strong>
  {% for time_slot in date_time_options %}
      {% if time_slot.voter_name %}
      <li>
        {{ time_slot.voter_name }} voted {{ time_slot.date_time|date:"M. d, Y, h:i a" }}<br>

        </li>

      {% endif %}
  {% endfor %}

  {% if user.is_authenticated %}
<!-- Copy link to clipboard -->
<button class="btn" id="copy-link-btn">Copy Event Link</button>

<input type="text" id="event-link" value="{{ request.build_absolute_uri|safe }}" style="position: absolute; left: -9999px;" readonly>

<script>
    function copyEventLink() {
        var copyLink = document.getElementById("event-link");
        copyLink.select();
        document.execCommand("copy");
        alert("Event link copied to clipboard!");
    }
    var copyLinkBtn = document.getElementById("copy-link-btn");
    copyLinkBtn.addEventListener("click", copyEventLink);
</script>
{% endif %}

{% endblock %}

</body>
</html>

pokus/templates/pokus/includes/messages.html
{% for message in messages %}  
<div class="container-fluid p-0">
    <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="True">&times;</span>
      </button>
      {{ message }}
    </div>
</div>
{% endfor %} 

pokus/templates/pokus/login.html
<!-- login.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login Form</title>
    <!-- Link to the CSS file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/form_styles.css' %}">
    <!-- Font Awesome for social media icons -->
    <script src="https://kit.fontawesome.com/1ab94d0eba.js" crossorigin="anonymous"></script>
</head>
<body>
    <main class="container">
        <h2>Login</h2>

        <!-- Display Messages -->
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <form action="{% url 'pokus:login' %}" method="POST">
            {% csrf_token %}
            <div class="input-field">
                <input type="text" name="username" id="username" placeholder="Enter Your Username" required value="{{ request.POST.username }}">
                <div class="underline"></div>
                {% if login_form.username.errors %}
                    {% for error in login_form.username.errors %}
                        <span class="error">{{ error }}</span>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="input-field">
                <input type="password" name="password" id="password" placeholder="Enter Your Password" required>
                <div class="underline"></div>
                {% if login_form.password.errors %}
                    {% for error in login_form.password.errors %}
                        <span class="error">{{ error }}</span>
                    {% endfor %}
                {% endif %}
            </div>

            <input type="submit" value="Continue">
        </form>

        <!-- Social Media Login -->
        <div class="footer">
            <span>Or Connect With Social Media</span>
            <div class="social-fields">
                <div class="social-field twitter">
                    <a href="#">
                        <i class="fab fa-twitter"></i>
                        Sign in with Twitter
                    </a>
                </div>
                <div class="social-field facebook">
                    <a href="#">
                        <i class="fab fa-facebook-f"></i>
                        Sign in with Facebook
                    </a>
                </div>
            </div>
        </div>

         <!-- Registration prompt -->
         <div class="login-prompt">
            <span>Don't have an account? <a href="{% url 'pokus:register' %}">Sign up</a></span>
        </div>
        
    </main>
</body>
</html>

pokus/templates/pokus/login1.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}
form {border: 3px solid #f1f1f1;} 

input[type=text], input[type=password] {
	width: 100%;
	padding: 15px;
	margin: 5px 0 22px 0;
	display: inline-block;
	border: none;
	background: #f1f1f1;
}

* {
  box-sizing: border-box;
}

.container {
  padding: 16px;
  background-color: white;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

button {
  background-color: #0f5e61;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

button:hover {
  opacity: 1;
}

a {
  color: #0f5e61;
}

.login {
  background-color: #f1f1f1;
  text-align: center;
}

</style>
</head>
<body>

<form method="post">

  {% csrf_token %}
  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
          <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}
  <div class="container">
    <h1>Log in </h1>
    <hr>

    <label for="username"><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="username" required>

    <label for="password"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="password" required>
        
    <button type="submit">Log in</button>
  </div>

  <div class="container login">
    <p> Don't have an account? <a href="/pokus/register">Create an account</a>.</p>
  </div>
</form>

</body>
</html>

pokus/templates/pokus/register.html
<!-- register.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register Form</title>
    <!-- Link to the CSS file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/form_styles.css' %}">
    <!-- Font Awesome for social media icons -->
    <script src="https://kit.fontawesome.com/1ab94d0eba.js" crossorigin="anonymous"></script>
</head>
<body>
    <main class="container">
        <h2>Sign Up</h2>

        <!-- Display Messages -->
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <form action="{% url 'pokus:register' %}" method="POST">
            {% csrf_token %}
            <div class="input-field">
                <input type="text" name="username" id="username" placeholder="Enter Your Username" required value="{{ request.POST.username }}">
                <div class="underline"></div>
                {% if register_form.username.errors %}
                    {% for error in register_form.username.errors %}
                        <span class="error">{{ error }}</span>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="input-field">
                <input type="email" name="email" id="email" placeholder="Enter Your Email" required value="{{ request.POST.email }}">
                <div class="underline"></div>
                {% if register_form.email.errors %}
                    {% for error in register_form.email.errors %}
                        <span class="error">{{ error }}</span>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="input-field">
                <input type="password" name="password1" id="password1" placeholder="Enter Your Password" required>
                <div class="underline"></div>
                {% if register_form.password1.errors %}
                    {% for error in register_form.password1.errors %}
                        <span class="error">{{ error }}</span>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="input-field">
                <input type="password" name="password2" id="password2" placeholder="Confirm Your Password" required>
                <div class="underline"></div>
                {% if register_form.password2.errors %}
                    {% for error in register_form.password2.errors %}
                        <span class="error">{{ error }}</span>
                    {% endfor %}
                {% endif %}
            </div>

            <input type="submit" value="Continue">
        </form>

        <!-- Social Media Registration -->
        <div class="footer">
            <span>Or Connect With Social Media</span>
            <div class="social-fields">
                <div class="social-field twitter">
                    <a href="#">
                        <i class="fab fa-twitter"></i>
                        Sign up with Twitter
                    </a>
                </div>
                <div class="social-field facebook">
                    <a href="#">
                        <i class="fab fa-facebook-f"></i>
                        Sign up with Facebook
                    </a>
                </div>
            </div>
        </div>

        <!-- Login prompt -->
        <div class="login-prompt">
            <span>Already have an account? <a href="{% url 'pokus:login' %}">Log in</a></span>
        </div>
        
    </main>
</body>
</html>